import React, { useEffect, useState } from "react";
import { Loader2, Trash2 } from "lucide-react";
import { api } from "../../lib/api";
const STATUSES=["placed","confirmed","processing","shipped","delivered","cancelled"];
export default function AdminOrders(){
 const [orders,setOrders]=useState(null),[error,setError]=useState(""),[updating,setUpdating]=useState(""),[deleting,setDeleting]=useState("");
 const load=async()=>{setError("");try{const d=await api.allOrders();setOrders(Array.isArray(d)?d:[])}catch(e){setOrders([]);setError(e.message||"Could not load orders.")}};
 useEffect(()=>{let alive=true;(async()=>{try{const d=await api.allOrders();if(alive)setOrders(Array.isArray(d)?d:[])}catch(e){if(alive){setOrders([]);setError(e.message||"Could not load orders.")}}})();return()=>{alive=false}},[]);
 const updateStatus=async(o,status)=>{if(status===o.status)return;if(status==="cancelled"&&!confirm(`Cancel order ${o.id}? Stock will be restored.`))return;setUpdating(o.id);setError("");try{const saved=await api.updateOrderStatus(o.id,status);setOrders(cur=>(cur||[]).map(x=>x.id===o.id?saved:x))}catch(e){setError(e.message||"Could not update order.")}finally{setUpdating("")}};
 const remove=async(o)=>{if(!["delivered","cancelled"].includes(o.status))return;if(!confirm(`Delete order #${o.id}? This cannot be undone.`))return;setDeleting(o.id);try{await api.deleteOrder(o.id);setOrders(cur=>(cur||[]).filter(x=>x.id!==o.id))}catch(e){setError(e.message||"Could not delete order.")}finally{setDeleting("")}};
 if(orders===null)return <p className="text-xs opacity-60 mt-6">Loading orders…</p>;
 return <div className="mt-2 space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-display italic text-lg font-bold">Orders</h3><p className="text-xs opacity-50">{orders.length} order{orders.length===1?"":"s"}</p></div><button onClick={load} className="px-3 py-1.5 rounded-full border border-current/15 text-[10px] font-semibold uppercase">Refresh</button></div>{error&&<p className="text-xs text-[#A8431E] border border-[#A8431E]/20 rounded-lg px-3 py-2">{error}</p>}{orders.length===0?<p className="text-xs opacity-60">No orders placed yet.</p>:orders.map(o=>{const status=STATUSES.includes(o.status)?o.status:"placed";return <div key={o.id} className="border border-current/10 rounded-2xl p-4 text-sm"><div className="flex items-start justify-between gap-3 mb-3"><div><p className="font-mono text-xs font-semibold">#{o.id}</p><p className="text-xs opacity-55 mt-1">{o.email||"Guest email unavailable"}</p></div><p className="text-[10px] opacity-55">{o.createdAt?new Date(o.createdAt).toLocaleString():"—"}</p></div><p className="opacity-80">{(o.items||[]).map(it=>`${it?.name||"Item"} ×${Number(it?.qty||0)}`).join(", ")||"No item details"}</p>{o.shipping&&<p className="text-xs opacity-50 mt-2">{o.shipping.fullName||""} · {o.shipping.phone||""} · {o.shipping.line1||""}, {o.shipping.city||""}</p>}<div className="flex items-center justify-between gap-3 mt-4 flex-wrap"><div><p className="font-mono font-semibold">${Number(o.total||0).toFixed(2)}</p><p className="text-[10px] uppercase opacity-50 mt-1">{o.paymentMethod||"payment"} · {o.paymentRef||"—"}</p></div><div className="flex gap-2"><select value={status} disabled={updating===o.id||deleting===o.id} onChange={e=>updateStatus(o,e.target.value)} className="px-3 py-2 rounded-lg border border-current/15 bg-transparent text-xs capitalize">{STATUSES.map(s=><option key={s} value={s}>{s}</option>)}</select>{["delivered","cancelled"].includes(status)&&<button onClick={()=>remove(o)} disabled={deleting===o.id} title="Delete order" className="w-9 h-9 rounded-lg border border-[#A8431E]/25 text-[#A8431E] flex items-center justify-center">{deleting===o.id?<Loader2 size={13} className="animate-spin"/>:<Trash2 size={13}/>}</button>}</div></div></div>})}</div>
}
